-- PlaySpace initial schema.
-- Kept portable between PostgreSQL and H2 running in PostgreSQL compatibility mode.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    avatar_url VARCHAR(255),
    bio VARCHAR(255),
    city VARCHAR(255),
    member_since DATE,
    favorite_modality VARCHAR(255),
    sports_level VARCHAR(255),
    reservations_done INTEGER NOT NULL,
    matches_played INTEGER NOT NULL,
    hours_on_court DOUBLE PRECISION NOT NULL,
    attendance_rate DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'CLIENTE')),
    CONSTRAINT ck_users_favorite_modality CHECK (
        favorite_modality IS NULL OR favorite_modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')
    ),
    CONSTRAINT ck_users_metrics CHECK (
        reservations_done >= 0 AND matches_played >= 0 AND hours_on_court >= 0
        AND attendance_rate >= 0 AND attendance_rate <= 100
    )
);

CREATE TABLE user_sports (
    user_id BIGINT NOT NULL,
    sport VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_sports PRIMARY KEY (user_id, sport),
    CONSTRAINT fk_user_sports_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_achievements (
    user_id BIGINT NOT NULL,
    achievement VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_achievements PRIMARY KEY (user_id, achievement),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE court (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    modality VARCHAR(255) NOT NULL,
    description VARCHAR(1200),
    price_per_hour NUMERIC(10, 2) NOT NULL,
    player_capacity INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    location VARCHAR(255),
    lighting BOOLEAN NOT NULL,
    covered BOOLEAN NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_court_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')),
    CONSTRAINT ck_court_status CHECK (status IN ('DISPONIVEL', 'EM_MANUTENCAO', 'INDISPONIVEL')),
    CONSTRAINT ck_court_price CHECK (price_per_hour > 0),
    CONSTRAINT ck_court_capacity CHECK (player_capacity > 0),
    CONSTRAINT ck_court_rating CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    modality VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    players INTEGER NOT NULL,
    total_value NUMERIC(10, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255),
    notes VARCHAR(1000),
    history VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_reservation_code UNIQUE (code),
    CONSTRAINT fk_reservation_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_reservation_court FOREIGN KEY (court_id) REFERENCES court (id),
    CONSTRAINT ck_reservation_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')),
    CONSTRAINT ck_reservation_status CHECK (status IN ('PENDENTE', 'CONFIRMADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT ck_reservation_payment_method CHECK (
        payment_method IS NULL OR payment_method IN ('PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO')
    ),
    CONSTRAINT ck_reservation_time CHECK (start_time < end_time),
    CONSTRAINT ck_reservation_players CHECK (players > 0),
    CONSTRAINT ck_reservation_total CHECK (total_value >= 0)
);

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    transaction_code VARCHAR(255),
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_payment_transaction_code UNIQUE (transaction_code),
    CONSTRAINT fk_payment_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT ck_payment_method CHECK (method IN ('PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO')),
    CONSTRAINT ck_payment_status CHECK (status IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO')),
    CONSTRAINT ck_payment_amount CHECK (amount >= 0)
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1200) NOT NULL,
    type VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE community_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    content VARCHAR(1200) NOT NULL,
    type VARCHAR(255) NOT NULL,
    likes INTEGER NOT NULL,
    comments INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_community_post_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT ck_community_post_counters CHECK (likes >= 0 AND comments >= 0)
);

CREATE TABLE partner_ad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    modality VARCHAR(255) NOT NULL,
    level VARCHAR(255),
    city VARCHAR(255),
    availability VARCHAR(255),
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_partner_ad_player FOREIGN KEY (player_id) REFERENCES users (id),
    CONSTRAINT ck_partner_ad_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE'))
);

CREATE TABLE championship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    modality VARCHAR(255) NOT NULL,
    start_date DATE,
    categories VARCHAR(255),
    prize VARCHAR(255),
    status VARCHAR(255),
    regulation VARCHAR(1600),
    bracket_demo VARCHAR(1600),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_championship_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE'))
);

CREATE TABLE achievement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    icon VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    progress INTEGER NOT NULL,
    target_value INTEGER NOT NULL,
    percent_complete DOUBLE PRECISION NOT NULL,
    unlocked_at DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_achievement_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_achievement_progress CHECK (progress >= 0 AND target_value > 0),
    CONSTRAINT ck_achievement_percent CHECK (percent_complete >= 0 AND percent_complete <= 100)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    cleaning INTEGER NOT NULL,
    lighting INTEGER NOT NULL,
    organization INTEGER NOT NULL,
    service INTEGER NOT NULL,
    court_quality INTEGER NOT NULL,
    average DOUBLE PRECISION NOT NULL,
    comment VARCHAR(1200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_review_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_review_court FOREIGN KEY (court_id) REFERENCES court (id),
    CONSTRAINT ck_review_ratings CHECK (
        cleaning BETWEEN 1 AND 5 AND lighting BETWEEN 1 AND 5
        AND organization BETWEEN 1 AND 5 AND service BETWEEN 1 AND 5
        AND court_quality BETWEEN 1 AND 5 AND average BETWEEN 0 AND 5
    )
);

CREATE INDEX idx_users_role_active ON users (role, active);
CREATE INDEX idx_court_status_modality ON court (status, modality);
CREATE INDEX idx_reservation_client_date_time ON reservation (client_id, date, start_time);
CREATE INDEX idx_reservation_court_conflict ON reservation (court_id, date, status, start_time, end_time);
CREATE INDEX idx_reservation_status_date ON reservation (status, date);
CREATE INDEX idx_reservation_modality_date ON reservation (modality, date);
CREATE INDEX idx_payment_reservation_status ON payment (reservation_id, status);
CREATE INDEX idx_payment_status_created_at ON payment (status, created_at);
CREATE INDEX idx_notification_user_read_created ON notification (user_id, is_read, created_at);
CREATE INDEX idx_activity_log_created_at ON activity_log (created_at);
CREATE INDEX idx_community_post_created_at ON community_post (created_at);
CREATE INDEX idx_partner_ad_created_at ON partner_ad (created_at);
CREATE INDEX idx_championship_start_date ON championship (start_date);
CREATE INDEX idx_achievement_user_percent ON achievement (user_id, percent_complete);
CREATE INDEX idx_review_created_at ON review (created_at);
