-- Persisted Community interactions: optional sport context, comments and idempotent likes.

ALTER TABLE community_post ADD COLUMN modality VARCHAR(255);

ALTER TABLE community_post
    ADD CONSTRAINT ck_community_post_modality CHECK (
        modality IS NULL OR modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')
    );

CREATE TABLE community_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(800) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_community_comment_post FOREIGN KEY (post_id) REFERENCES community_post (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_comment_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE community_post_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_community_post_like_post FOREIGN KEY (post_id) REFERENCES community_post (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_post_like_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_community_post_like_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_community_comment_post_created ON community_comment (post_id, created_at);
CREATE INDEX idx_community_comment_author ON community_comment (author_id);
CREATE INDEX idx_community_post_like_post ON community_post_like (post_id);
CREATE INDEX idx_community_post_like_user ON community_post_like (user_id);
