-- Complete account, preferences, platform settings, championships and partner discovery domains.
-- SQL kept portable between PostgreSQL and H2 (PostgreSQL compatibility mode).

ALTER TABLE users ADD COLUMN phone VARCHAR(30);
ALTER TABLE users ADD COLUMN availability VARCHAR(1000);

CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    theme VARCHAR(20) NOT NULL,
    notifications_enabled BOOLEAN NOT NULL,
    reservation_reminder_hours INTEGER NOT NULL,
    email_notifications BOOLEAN NOT NULL,
    browser_notifications BOOLEAN NOT NULL,
    default_city VARCHAR(120),
    favorite_modalities VARCHAR(500),
    preferred_times VARCHAR(1000),
    private_profile BOOLEAN NOT NULL,
    discoverable_by_partners BOOLEAN NOT NULL,
    language VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_preferences_user UNIQUE (user_id),
    CONSTRAINT ck_user_preferences_reminder CHECK (reservation_reminder_hours BETWEEN 0 AND 168)
);

CREATE TABLE platform_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(160) NOT NULL,
    legal_name VARCHAR(160),
    document VARCHAR(30),
    company_email VARCHAR(254),
    company_phone VARCHAR(30),
    address VARCHAR(255),
    timezone VARCHAR(60) NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    operating_days VARCHAR(100) NOT NULL,
    cancellation_rule_hours INTEGER NOT NULL,
    minimum_reservation_minutes INTEGER NOT NULL,
    maximum_advance_days INTEGER NOT NULL,
    slot_minutes INTEGER NOT NULL,
    enabled_modalities VARCHAR(200) NOT NULL,
    beach_tennis_price NUMERIC(10, 2) NOT NULL,
    futevolei_price NUMERIC(10, 2) NOT NULL,
    society_price NUMERIC(10, 2) NOT NULL,
    tenis_price NUMERIC(10, 2) NOT NULL,
    volei_price NUMERIC(10, 2) NOT NULL,
    basquete_price NUMERIC(10, 2) NOT NULL,
    accept_pix BOOLEAN NOT NULL,
    accept_card BOOLEAN NOT NULL,
    accept_cash BOOLEAN NOT NULL,
    pix_key VARCHAR(254),
    email_notifications BOOLEAN NOT NULL,
    browser_notifications BOOLEAN NOT NULL,
    reservation_reminder_hours INTEGER NOT NULL,
    primary_color VARCHAR(20) NOT NULL,
    logo_url VARCHAR(255),
    default_theme VARCHAR(20) NOT NULL,
    minimum_password_length INTEGER NOT NULL,
    session_minutes INTEGER NOT NULL,
    require_strong_password BOOLEAN NOT NULL,
    public_registration_enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_platform_settings_hours CHECK (opening_time < closing_time),
    CONSTRAINT ck_platform_settings_reservation CHECK (
        cancellation_rule_hours >= 0 AND minimum_reservation_minutes > 0
        AND maximum_advance_days > 0 AND slot_minutes > 0
    ),
    CONSTRAINT ck_platform_settings_prices CHECK (
        beach_tennis_price >= 0 AND futevolei_price >= 0 AND society_price >= 0
        AND tenis_price >= 0 AND volei_price >= 0 AND basquete_price >= 0
    )
);

INSERT INTO platform_settings (
    company_name, legal_name, document, company_email, company_phone, address, timezone,
    opening_time, closing_time, operating_days, cancellation_rule_hours,
    minimum_reservation_minutes, maximum_advance_days, slot_minutes, enabled_modalities,
    beach_tennis_price, futevolei_price, society_price, tenis_price, volei_price, basquete_price,
    accept_pix, accept_card, accept_cash, pix_key, email_notifications, browser_notifications,
    reservation_reminder_hours, primary_color, logo_url, default_theme, minimum_password_length,
    session_minutes, require_strong_password, public_registration_enabled, created_at, updated_at
) VALUES (
    'PlaySpace', 'PlaySpace Gestão Esportiva Ltda.', NULL, 'contato@playspace.com', '(11) 4000-2026',
    'São Paulo - SP', 'America/Sao_Paulo', '06:00:00', '23:00:00',
    'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY', 12, 60, 90, 60,
    'BASQUETE,BEACH_TENNIS,FUTEVOLEI,SOCIETY,TENIS,VOLEI',
    120.00, 110.00, 180.00, 115.00, 95.00, 90.00,
    TRUE, TRUE, FALSE, 'contato@playspace.com', TRUE, TRUE, 2,
    '#0F766E', NULL, 'SYSTEM', 8, 120, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

CREATE TABLE championship_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1600) NOT NULL,
    modality VARCHAR(40) NOT NULL,
    court_id BIGINT NOT NULL,
    location VARCHAR(255) NOT NULL,
    city VARCHAR(120) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    registration_deadline DATE NOT NULL,
    max_participants INTEGER NOT NULL,
    format VARCHAR(120) NOT NULL,
    prize VARCHAR(255) NOT NULL,
    registration_fee NUMERIC(10, 2) NOT NULL,
    regulation VARCHAR(6000) NOT NULL,
    status VARCHAR(40) NOT NULL,
    image_url VARCHAR(500),
    bracket VARCHAR(6000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_championship_event_court FOREIGN KEY (court_id) REFERENCES court (id),
    CONSTRAINT ck_championship_event_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')),
    CONSTRAINT ck_championship_event_status CHECK (status IN ('RASCUNHO', 'INSCRICOES_ABERTAS', 'INSCRICOES_ENCERRADAS', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT ck_championship_event_dates CHECK (start_date <= end_date AND registration_deadline <= start_date),
    CONSTRAINT ck_championship_event_capacity CHECK (max_participants > 0 AND registration_fee >= 0),
    CONSTRAINT uk_championship_event_name_date UNIQUE (name, start_date)
);

CREATE TABLE championship_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_championship_enrollment_event FOREIGN KEY (championship_id) REFERENCES championship_event (id) ON DELETE CASCADE,
    CONSTRAINT fk_championship_enrollment_player FOREIGN KEY (player_id) REFERENCES users (id),
    CONSTRAINT uk_championship_enrollment_player UNIQUE (championship_id, player_id),
    CONSTRAINT ck_championship_enrollment_status CHECK (status IN ('ATIVA', 'CANCELADA'))
);

CREATE TABLE sports_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    city VARCHAR(120) NOT NULL,
    objective VARCHAR(40) NOT NULL,
    presentation VARCHAR(1200) NOT NULL,
    position VARCHAR(120),
    discoverable BOOLEAN NOT NULL,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sports_profile_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_sports_profile_user UNIQUE (user_id),
    CONSTRAINT ck_sports_profile_objective CHECK (objective IN ('TREINO', 'JOGO_CASUAL', 'COMPETICAO', 'ENCONTRAR_TIME'))
);

CREATE TABLE sports_profile_region (
    profile_id BIGINT NOT NULL,
    region VARCHAR(120) NOT NULL,
    CONSTRAINT pk_sports_profile_region PRIMARY KEY (profile_id, region),
    CONSTRAINT fk_sports_profile_region_profile FOREIGN KEY (profile_id) REFERENCES sports_profile (id) ON DELETE CASCADE
);

CREATE TABLE sports_profile_modality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    modality VARCHAR(40) NOT NULL,
    level VARCHAR(40) NOT NULL,
    primary_modality BOOLEAN NOT NULL,
    CONSTRAINT fk_sports_profile_modality_profile FOREIGN KEY (profile_id) REFERENCES sports_profile (id) ON DELETE CASCADE,
    CONSTRAINT uk_profile_modality UNIQUE (profile_id, modality),
    CONSTRAINT ck_sports_profile_modality CHECK (modality IN ('BEACH_TENNIS', 'FUTEVOLEI', 'SOCIETY', 'TENIS', 'VOLEI', 'BASQUETE')),
    CONSTRAINT ck_sports_profile_level CHECK (level IN ('INICIANTE', 'INTERMEDIARIO', 'AVANCADO', 'COMPETITIVO'))
);

CREATE TABLE sports_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    day_of_week VARCHAR(16) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_sports_availability_profile FOREIGN KEY (profile_id) REFERENCES sports_profile (id) ON DELETE CASCADE,
    CONSTRAINT ck_sports_availability_time CHECK (start_time < end_time),
    CONSTRAINT ck_sports_availability_day CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE partner_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    message VARCHAR(500),
    responded_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_partner_interest_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_partner_interest_receiver FOREIGN KEY (receiver_id) REFERENCES users (id),
    CONSTRAINT uk_partner_interest_pair UNIQUE (sender_id, receiver_id),
    CONSTRAINT ck_partner_interest_distinct_users CHECK (sender_id <> receiver_id),
    CONSTRAINT ck_partner_interest_status CHECK (status IN ('PENDENTE', 'ACEITO', 'RECUSADO', 'CANCELADO'))
);

CREATE INDEX idx_user_preferences_user ON user_preferences (user_id);
CREATE INDEX idx_championship_event_search ON championship_event (status, modality, city, start_date);
CREATE INDEX idx_championship_enrollment_event_status ON championship_enrollment (championship_id, status);
CREATE INDEX idx_championship_enrollment_player ON championship_enrollment (player_id, created_at);
CREATE INDEX idx_sports_profile_discovery ON sports_profile (discoverable, city, objective);
CREATE INDEX idx_sports_profile_modality_search ON sports_profile_modality (modality, level);
CREATE INDEX idx_partner_interest_sender_status ON partner_interest (sender_id, status);
CREATE INDEX idx_partner_interest_receiver_status ON partner_interest (receiver_id, status);
