-- Dynamic sport modality catalog. Existing domain rows continue to store stable modality codes.
-- SQL is portable between PostgreSQL and H2 in PostgreSQL compatibility mode.

CREATE TABLE sport_modality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    default_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_sport_modality_code UNIQUE (code),
    CONSTRAINT uk_sport_modality_normalized_name UNIQUE (normalized_name),
    CONSTRAINT ck_sport_modality_price CHECK (default_price >= 0)
);

-- Carry forward prices already configured by each installation.
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'BEACH_TENNIS', 'Beach Tennis', 'beach tennis',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,BEACH_TENNIS,%' THEN TRUE ELSE FALSE END,
       beach_tennis_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'FUTEVOLEI', 'Futevôlei', 'futevolei',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,FUTEVOLEI,%' THEN TRUE ELSE FALSE END,
       futevolei_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'SOCIETY', 'Society', 'society',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,SOCIETY,%' THEN TRUE ELSE FALSE END,
       society_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'TENIS', 'Tênis', 'tenis',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,TENIS,%' THEN TRUE ELSE FALSE END,
       tenis_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'VOLEI', 'Vôlei', 'volei',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,VOLEI,%' THEN TRUE ELSE FALSE END,
       volei_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);
INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'BASQUETE', 'Basquete', 'basquete',
       CASE WHEN (',' || enabled_modalities || ',') LIKE '%,BASQUETE,%' THEN TRUE ELSE FALSE END,
       basquete_price, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM platform_settings WHERE id = (SELECT MIN(id) FROM platform_settings);

-- The catalog is now the single source of truth for availability and prices.
ALTER TABLE platform_settings DROP CONSTRAINT ck_platform_settings_prices;
ALTER TABLE platform_settings DROP COLUMN enabled_modalities;
ALTER TABLE platform_settings DROP COLUMN beach_tennis_price;
ALTER TABLE platform_settings DROP COLUMN futevolei_price;
ALTER TABLE platform_settings DROP COLUMN society_price;
ALTER TABLE platform_settings DROP COLUMN tenis_price;
ALTER TABLE platform_settings DROP COLUMN volei_price;
ALTER TABLE platform_settings DROP COLUMN basquete_price;

ALTER TABLE users DROP CONSTRAINT ck_users_favorite_modality;
ALTER TABLE court DROP CONSTRAINT ck_court_modality;
ALTER TABLE reservation DROP CONSTRAINT ck_reservation_modality;
ALTER TABLE community_post DROP CONSTRAINT ck_community_post_modality;
ALTER TABLE partner_ad DROP CONSTRAINT ck_partner_ad_modality;
ALTER TABLE championship DROP CONSTRAINT ck_championship_modality;
ALTER TABLE championship_event DROP CONSTRAINT ck_championship_event_modality;
ALTER TABLE sports_profile_modality DROP CONSTRAINT ck_sports_profile_modality;

-- Earlier versions stored free-form display labels in this element collection. First materialize
-- every historical value in the catalog, then replace labels with stable codes. This keeps custom
-- sports created before V6 and prevents the new FK from making an existing installation unbootable.
CREATE TABLE user_sports_source (
    user_id BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255),
    known_code VARCHAR(40)
);

INSERT INTO user_sports_source (user_id, display_name)
SELECT user_id,
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(sport), '  ', ' '), '  ', ' '), '  ', ' '), '  ', ' '), '  ', ' ')
FROM user_sports
WHERE TRIM(sport) <> '';

UPDATE user_sports_source
SET normalized_name = LOWER(TRANSLATE(
        display_name,
        'áàâãäéèêëíìîïóòôõöúùûüçñ',
        'aaaaaeeeeiiiiooooouuuucn'
    ));

UPDATE user_sports_source
SET known_code = CASE
    WHEN normalized_name IN ('beach tennis', 'beach_tennis') THEN 'BEACH_TENNIS'
    WHEN normalized_name = 'futevolei' THEN 'FUTEVOLEI'
    WHEN normalized_name = 'society' THEN 'SOCIETY'
    WHEN normalized_name = 'tenis' THEN 'TENIS'
    WHEN normalized_name = 'volei' THEN 'VOLEI'
    WHEN normalized_name = 'basquete' THEN 'BASQUETE'
    ELSE NULL
END;

INSERT INTO sport_modality (code, name, normalized_name, active, default_price, created_at, updated_at)
SELECT 'LEGACY_' || CAST(ROW_NUMBER() OVER (ORDER BY normalized_name) AS VARCHAR(20)),
       MIN(display_name), normalized_name, TRUE, 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM user_sports_source
WHERE known_code IS NULL
GROUP BY normalized_name;

CREATE TABLE user_sports_migrated (
    user_id BIGINT NOT NULL,
    sport VARCHAR(255) NOT NULL
);

INSERT INTO user_sports_migrated (user_id, sport)
SELECT user_id, known_code
FROM user_sports_source
WHERE known_code IS NOT NULL
UNION
SELECT source.user_id, catalog.code
FROM user_sports_source source
JOIN sport_modality catalog ON catalog.normalized_name = source.normalized_name
WHERE source.known_code IS NULL;

DELETE FROM user_sports;
INSERT INTO user_sports (user_id, sport)
SELECT user_id, sport FROM user_sports_migrated;
DROP TABLE user_sports_migrated;
DROP TABLE user_sports_source;

ALTER TABLE users
    ADD CONSTRAINT fk_users_favorite_modality_catalog
    FOREIGN KEY (favorite_modality) REFERENCES sport_modality (code);
ALTER TABLE court
    ADD CONSTRAINT fk_court_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE reservation
    ADD CONSTRAINT fk_reservation_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE community_post
    ADD CONSTRAINT fk_community_post_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE partner_ad
    ADD CONSTRAINT fk_partner_ad_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE championship
    ADD CONSTRAINT fk_championship_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE championship_event
    ADD CONSTRAINT fk_championship_event_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE sports_profile_modality
    ADD CONSTRAINT fk_sports_profile_modality_catalog
    FOREIGN KEY (modality) REFERENCES sport_modality (code);
ALTER TABLE user_sports
    ADD CONSTRAINT fk_user_sports_catalog
    FOREIGN KEY (sport) REFERENCES sport_modality (code);

CREATE INDEX idx_sport_modality_active_name ON sport_modality (active, name);
