import { CalendarClock, Check, Edit3, Mail, MapPin, Plus, Search, Send, Trash2, UserRoundSearch, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { Avatar } from '../../components/Avatar';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { EmptyState } from '../../components/EmptyState';
import { Modal } from '../../components/Modal';
import { Toast } from '../../components/Toast';
import { useAppData } from '../../contexts/AppDataContext';
import { useAuth } from '../../contexts/AuthContext';
import type { Modality, PartnerObjective, SportsLevel, SportsProfile, WeekDay } from '../../lib/types';

const modalities: Modality[] = ['Beach Tennis', 'Futevôlei', 'Society', 'Tênis', 'Vôlei', 'Basquete'];
const levels: SportsLevel[] = ['INICIANTE', 'INTERMEDIARIO', 'AVANCADO', 'COMPETITIVO'];
const objectives: PartnerObjective[] = ['TREINO', 'JOGO_CASUAL', 'COMPETICAO', 'ENCONTRAR_TIME'];
const days: WeekDay[] = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'];
const levelLabels: Record<SportsLevel, string> = { INICIANTE: 'Iniciante', INTERMEDIARIO: 'Intermediário', AVANCADO: 'Avançado', COMPETITIVO: 'Competitivo' };
const objectiveLabels: Record<PartnerObjective, string> = { TREINO: 'Treino', JOGO_CASUAL: 'Jogo casual', COMPETICAO: 'Competição', ENCONTRAR_TIME: 'Encontrar time' };
const dayLabels: Record<WeekDay, string> = { MONDAY: 'Segunda-feira', TUESDAY: 'Terça-feira', WEDNESDAY: 'Quarta-feira', THURSDAY: 'Quinta-feira', FRIDAY: 'Sexta-feira', SATURDAY: 'Sábado', SUNDAY: 'Domingo' };
const statusLabels = { PENDENTE: 'Pendente', ACEITO: 'Aceito', RECUSADO: 'Recusado', CANCELADO: 'Cancelado' } as const;

export function PartnersPage() {
  const { user } = useAuth();
  const { state, cancelPartnerInterest, respondPartnerInterest, saveSportsProfile, sendPartnerInterest } = useAppData();
  const [query, setQuery] = useState('');
  const [city, setCity] = useState('');
  const [modality, setModality] = useState('');
  const [level, setLevel] = useState('');
  const [objective, setObjective] = useState('');
  const [visible, setVisible] = useState(6);
  const [profileOpen, setProfileOpen] = useState(false);
  const [requestsOpen, setRequestsOpen] = useState(false);
  const [requestDirection, setRequestDirection] = useState<'RECEBIDOS' | 'ENVIADOS'>('RECEBIDOS');
  const [interestTarget, setInterestTarget] = useState<SportsProfile | null>(null);
  const [interestMessage, setInterestMessage] = useState('');
  const [cancelInterestId, setCancelInterestId] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const ownProfile = state.sportsProfiles.find((item) => item.userId === user?.id);
  const [draft, setDraft] = useState<SportsProfile | null>(null);
  if (!user) return null;

  const createProfile = (): SportsProfile => ownProfile ? JSON.parse(JSON.stringify(ownProfile)) as SportsProfile : {
    id: '', userId: user.id, name: user.name, avatarUrl: user.profile.photo, city: user.profile.city === 'Não informada' ? '' : user.profile.city,
    regions: [], primaryModality: user.profile.favoriteModality,
    modalities: [{ modality: user.profile.favoriteModality, level: user.profile.level === 'Intermediário' ? 'INTERMEDIARIO' : user.profile.level === 'Avançado' ? 'AVANCADO' : user.profile.level === 'Competitivo' ? 'COMPETITIVO' : 'INICIANTE', primary: true }],
    availabilities: [], objective: 'JOGO_CASUAL', presentation: user.profile.bio, discoverable: true
  };

  const profiles = useMemo(() => state.sportsProfiles
    .filter((item) => item.userId !== user.id && item.discoverable)
    .filter((item) => `${item.name} ${item.city} ${item.regions.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
    .filter((item) => !city || item.city.toLowerCase().includes(city.toLowerCase()))
    .filter((item) => !modality || item.modalities.some((entry) => entry.modality === modality))
    .filter((item) => !level || item.modalities.some((entry) => entry.level === level))
    .filter((item) => !objective || item.objective === objective), [city, level, modality, objective, query, state.sportsProfiles, user.id]);
  const interests = state.partnerInterests.filter((item) => requestDirection === 'RECEBIDOS' ? item.receiverId === user.id : item.senderId === user.id);
  const pendingReceived = state.partnerInterests.filter((item) => item.receiverId === user.id && item.status === 'PENDENTE').length;

  const openProfile = () => { setDraft(createProfile()); setError(''); setProfileOpen(true); };
  const submitProfile = async (event: FormEvent) => {
    event.preventDefault(); if (!draft || submitting) return;
    setSubmitting(true); setError('');
    try { await saveSportsProfile(draft); setProfileOpen(false); setToast('Perfil esportivo salvo.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar o perfil esportivo.'); }
    finally { setSubmitting(false); }
  };
  const submitInterest = async (event: FormEvent) => {
    event.preventDefault(); if (!interestTarget || submitting) return;
    setSubmitting(true); setError('');
    try { await sendPartnerInterest(interestTarget.userId, interestMessage, user); setInterestTarget(null); setInterestMessage(''); setToast('Interesse enviado.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível enviar o interesse.'); }
    finally { setSubmitting(false); }
  };
  const respond = async (id: string, accept: boolean) => {
    setSubmitting(true); setError('');
    try { await respondPartnerInterest(id, accept, user); setToast(accept ? 'Interesse aceito. O contato foi liberado.' : 'Interesse recusado.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível responder.'); }
    finally { setSubmitting(false); }
  };

  return <>
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase text-neon">Conexões esportivas</p><h1 className="mt-1 text-3xl font-black">Encontrar parceiros</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Configure sua disponibilidade, encontre jogadores compatíveis e gerencie solicitações com segurança.</p></div><div className="flex flex-wrap gap-2"><button className="ghost-button relative min-h-11 rounded-lg px-4 py-2 font-bold" type="button" onClick={() => setRequestsOpen(true)}>Solicitações{pendingReceived > 0 && <span className="ml-2 rounded-full bg-neon px-2 py-0.5 text-xs font-black text-black">{pendingReceived}</span>}</button><button className="neon-button inline-flex min-h-11 items-center gap-2 rounded-lg px-4 py-2 font-black" type="button" onClick={openProfile}><Edit3 className="h-4 w-4" /> Meu perfil esportivo</button></div></header>

    {!ownProfile && <div className="mb-4 rounded-lg border border-amber/30 bg-amber/10 p-4 text-sm"><strong className="block text-amber">Complete seu perfil esportivo</strong><span className="text-muted">Cidade, modalidades e horários ajudam o PlaySpace a encontrar parceiros compatíveis.</span><button className="ml-2 font-black text-neon underline" type="button" onClick={openProfile}>Configurar agora</button></div>}

    <section className="glass-panel mb-4 rounded-lg p-4" aria-label="Filtros de parceiros"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="relative"><span className="sr-only">Buscar por nome</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted" /><input className="app-input w-full pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome ou região" /></label><input className="app-input" aria-label="Cidade" value={city} onChange={(event) => setCity(event.target.value)} placeholder="Cidade" /><select className="app-input" aria-label="Modalidade" value={modality} onChange={(event) => setModality(event.target.value)}><option value="">Todas as modalidades</option>{modalities.map((item) => <option key={item}>{item}</option>)}</select><select className="app-input" aria-label="Nível" value={level} onChange={(event) => setLevel(event.target.value)}><option value="">Todos os níveis</option>{levels.map((item) => <option key={item} value={item}>{levelLabels[item]}</option>)}</select><select className="app-input" aria-label="Objetivo" value={objective} onChange={(event) => setObjective(event.target.value)}><option value="">Todos os objetivos</option>{objectives.map((item) => <option key={item} value={item}>{objectiveLabels[item]}</option>)}</select></div></section>

    <section className="grid items-start gap-4 md:grid-cols-2 2xl:grid-cols-3">
      {profiles.slice(0, visible).map((profile) => {
        const main = profile.modalities.find((item) => item.primary) ?? profile.modalities[0];
        const interest = state.partnerInterests.find((item) => ((item.senderId === user.id && item.receiverId === profile.userId) || (item.senderId === profile.userId && item.receiverId === user.id)) && ['PENDENTE', 'ACEITO'].includes(item.status));
        return <article key={profile.id} className="glass-panel card-hover rounded-lg p-5"><div className="flex items-start gap-3"><Avatar name={profile.name} src={profile.avatarUrl ?? state.users.find((item) => item.id === profile.userId)?.profile.photo} size={52} /><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-black">{profile.name}</h2><p className="flex items-center gap-1 text-sm text-muted"><MapPin className="h-3.5 w-3.5" />{profile.city}{profile.regions[0] ? ` · ${profile.regions[0]}` : ''}</p></div><span className="rounded-full border border-neon/30 bg-neon/10 px-2.5 py-1 text-xs font-black text-neon">{main ? levelLabels[main.level] : 'Jogador'}</span></div><div className="mt-4 flex flex-wrap gap-2">{profile.modalities.map((item) => <span key={item.modality} className="rounded-full border border-line px-2.5 py-1 text-xs font-bold">{item.modality}</span>)}<span className="rounded-full border border-cyan/30 bg-cyan/10 px-2.5 py-1 text-xs font-bold text-cyan">{objectiveLabels[profile.objective]}</span></div><p className="mt-4 line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-muted">{profile.presentation}</p><div className="mt-4 border-t border-line pt-3"><p className="flex items-center gap-2 text-xs font-bold text-muted"><CalendarClock className="h-4 w-4 text-neon" />{profile.availabilities.length ? `${dayLabels[profile.availabilities[0].dayOfWeek]}, ${profile.availabilities[0].startTime}–${profile.availabilities[0].endTime}` : 'Disponibilidade a combinar'}</p><div className="mt-4 flex justify-end">{interest ? <span className="rounded-lg border border-line px-3 py-2 text-sm font-black">{statusLabels[interest.status]}</span> : <button className="neon-button inline-flex min-h-11 items-center gap-2 rounded-lg px-4 py-2 text-sm font-black" type="button" onClick={() => { setInterestTarget(profile); setInterestMessage(''); setError(''); }}><Send className="h-4 w-4" /> Tenho interesse</button>}</div></div></article>;
      })}
      {profiles.length === 0 && <div className="md:col-span-2 2xl:col-span-3"><EmptyState title="Nenhum parceiro encontrado" description="Ajuste os filtros ou amplie cidade, modalidade e nível." icon={UserRoundSearch} /></div>}
    </section>
    {visible < profiles.length && <div className="mt-4 text-center"><button className="ghost-button min-h-11 rounded-lg px-5 py-2 font-black" type="button" onClick={() => setVisible((value) => value + 6)}>Carregar mais</button></div>}

    <Modal title="Meu perfil esportivo" open={profileOpen} onClose={() => setProfileOpen(false)} maxWidth="max-w-4xl">{draft && <form className="grid gap-5" onSubmit={submitProfile}><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Cidade<input className="app-input" value={draft.city} onChange={(event) => setDraft({ ...draft, city: event.target.value })} required /></label><label className="grid gap-2 text-sm font-bold">Bairros ou regiões<input className="app-input" value={draft.regions.join(', ')} onChange={(event) => setDraft({ ...draft, regions: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="Pinheiros, Moema" /></label><label className="grid gap-2 text-sm font-bold">Objetivo<select className="app-input" value={draft.objective} onChange={(event) => setDraft({ ...draft, objective: event.target.value as PartnerObjective })}>{objectives.map((item) => <option key={item} value={item}>{objectiveLabels[item]}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Posição (quando aplicável)<input className="app-input" value={draft.position ?? ''} onChange={(event) => setDraft({ ...draft, position: event.target.value })} placeholder="Goleiro, atacante, armador..." /></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Apresentação<textarea className="app-input min-h-28 resize-y" value={draft.presentation} onChange={(event) => setDraft({ ...draft, presentation: event.target.value })} maxLength={1200} required /></label></div>
      <section><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Modalidades e níveis</h3><p className="text-xs text-muted">Marque uma modalidade como principal.</p></div><button className="ghost-button min-h-11 rounded-lg px-3 py-2 text-sm font-bold" type="button" onClick={() => { const available = modalities.find((item) => !draft.modalities.some((entry) => entry.modality === item)); if (available) setDraft({ ...draft, modalities: [...draft.modalities, { modality: available, level: 'INICIANTE', primary: false }] }); }} disabled={draft.modalities.length >= modalities.length}><Plus className="mr-1 inline h-4 w-4" />Adicionar</button></div><div className="mt-3 grid gap-3">{draft.modalities.map((entry, index) => <div key={`${entry.modality}-${index}`} className="soft-panel grid gap-3 rounded-lg p-3 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-end"><label className="grid gap-1 text-xs font-bold">Modalidade<select className="app-input" value={entry.modality} onChange={(event) => { const next = [...draft.modalities]; next[index] = { ...entry, modality: event.target.value as Modality }; setDraft({ ...draft, modalities: next }); }}>{modalities.map((item) => <option key={item} disabled={draft.modalities.some((current, currentIndex) => currentIndex !== index && current.modality === item)}>{item}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Nível<select className="app-input" value={entry.level} onChange={(event) => { const next = [...draft.modalities]; next[index] = { ...entry, level: event.target.value as SportsLevel }; setDraft({ ...draft, modalities: next }); }}>{levels.map((item) => <option key={item} value={item}>{levelLabels[item]}</option>)}</select></label><button className={`min-h-11 rounded-lg border px-3 py-2 text-sm font-black ${draft.primaryModality === entry.modality ? 'border-neon bg-neon/10 text-neon' : 'border-line text-muted'}`} type="button" onClick={() => setDraft({ ...draft, primaryModality: entry.modality })}>{draft.primaryModality === entry.modality ? 'Principal' : 'Tornar principal'}</button><button className="ghost-button min-h-11 rounded-lg p-2 text-[var(--danger)]" type="button" aria-label={`Remover ${entry.modality}`} disabled={draft.modalities.length === 1} onClick={() => { const remaining = draft.modalities.filter((_, current) => current !== index); setDraft({ ...draft, modalities: remaining, primaryModality: entry.modality === draft.primaryModality ? remaining[0].modality : draft.primaryModality }); }}><Trash2 className="mx-auto h-4 w-4" /></button></div>)}</div></section>
      <section><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Disponibilidade</h3><p className="text-xs text-muted">Adicione quantos horários forem necessários.</p></div><button className="ghost-button min-h-11 rounded-lg px-3 py-2 text-sm font-bold" type="button" onClick={() => setDraft({ ...draft, availabilities: [...draft.availabilities, { dayOfWeek: 'MONDAY', startTime: '18:00', endTime: '21:00' }] })}><Plus className="mr-1 inline h-4 w-4" />Adicionar horário</button></div><div className="mt-3 grid gap-3">{draft.availabilities.map((slot, index) => <div key={`${slot.dayOfWeek}-${index}`} className="soft-panel grid gap-3 rounded-lg p-3 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end"><label className="grid gap-1 text-xs font-bold">Dia<select className="app-input" value={slot.dayOfWeek} onChange={(event) => { const next = [...draft.availabilities]; next[index] = { ...slot, dayOfWeek: event.target.value as WeekDay }; setDraft({ ...draft, availabilities: next }); }}>{days.map((day) => <option key={day} value={day}>{dayLabels[day]}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Início<input className="app-input" type="time" value={slot.startTime} onChange={(event) => { const next = [...draft.availabilities]; next[index] = { ...slot, startTime: event.target.value }; setDraft({ ...draft, availabilities: next }); }} /></label><label className="grid gap-1 text-xs font-bold">Fim<input className="app-input" type="time" value={slot.endTime} onChange={(event) => { const next = [...draft.availabilities]; next[index] = { ...slot, endTime: event.target.value }; setDraft({ ...draft, availabilities: next }); }} /></label><button className="ghost-button min-h-11 rounded-lg p-2 text-[var(--danger)]" type="button" aria-label="Remover horário" onClick={() => setDraft({ ...draft, availabilities: draft.availabilities.filter((_, current) => current !== index) })}><Trash2 className="mx-auto h-4 w-4" /></button></div>)}{draft.availabilities.length === 0 && <p className="rounded-lg border border-dashed border-line p-5 text-center text-sm text-muted">Nenhum horário cadastrado.</p>}</div></section>
      <label className="soft-panel flex min-h-12 items-center gap-3 rounded-lg p-3 text-sm font-bold"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={draft.discoverable} onChange={(event) => setDraft({ ...draft, discoverable: event.target.checked })} />Permitir que outros jogadores encontrem meu perfil</label>
      {error && <p className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><button className="ghost-button min-h-11 rounded-lg px-4 py-2 font-bold" type="button" onClick={() => setProfileOpen(false)}>Cancelar</button><button className="neon-button min-h-11 rounded-lg px-4 py-2 font-black disabled:opacity-60" type="submit" disabled={submitting}>{submitting ? 'Salvando...' : 'Salvar perfil esportivo'}</button></div></form>}</Modal>

    <Modal title={`Interesse em ${interestTarget?.name ?? 'jogador'}`} open={Boolean(interestTarget)} onClose={() => setInterestTarget(null)} maxWidth="max-w-lg"><form className="grid gap-4" onSubmit={submitInterest}><div className="soft-panel flex items-center gap-3 rounded-lg p-3"><Avatar name={interestTarget?.name ?? ''} src={interestTarget?.avatarUrl} size={44} /><div><p className="font-black">{interestTarget?.name}</p><p className="text-sm text-muted">{interestTarget?.primaryModality} · {interestTarget?.city}</p></div></div><label className="grid gap-2 text-sm font-bold">Mensagem (opcional)<textarea className="app-input min-h-28 resize-y" value={interestMessage} onChange={(event) => setInterestMessage(event.target.value)} maxLength={500} placeholder="Apresente uma sugestão de dia ou objetivo..." /></label>{error && <p className="text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="flex justify-end gap-2"><button className="ghost-button min-h-11 rounded-lg px-4 py-2 font-bold" type="button" onClick={() => setInterestTarget(null)}>Cancelar</button><button className="neon-button min-h-11 rounded-lg px-4 py-2 font-black" type="submit" disabled={submitting}>{submitting ? 'Enviando...' : 'Enviar interesse'}</button></div></form></Modal>

    <Modal title="Solicitações de parceiros" open={requestsOpen} onClose={() => setRequestsOpen(false)} maxWidth="max-w-3xl"><div className="grid gap-4"><div className="grid grid-cols-2 gap-2">{(['RECEBIDOS', 'ENVIADOS'] as const).map((item) => <button key={item} className={`min-h-11 rounded-lg border px-3 py-2 text-sm font-black ${requestDirection === item ? 'border-neon bg-neon/10 text-neon' : 'border-line text-muted'}`} type="button" onClick={() => setRequestDirection(item)}>{item === 'RECEBIDOS' ? 'Recebidos' : 'Enviados'}</button>)}</div>{error && <p className="text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="grid gap-3">{interests.map((interest) => { const otherName = requestDirection === 'RECEBIDOS' ? interest.senderName : interest.receiverName; const otherAvatar = requestDirection === 'RECEBIDOS' ? interest.senderAvatarUrl : interest.receiverAvatarUrl; return <article key={interest.id} className="soft-panel rounded-lg p-4"><div className="flex items-start gap-3"><Avatar name={otherName} src={otherAvatar} size={42} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{otherName}</p><span className="rounded-full border border-line px-2.5 py-1 text-xs font-black">{statusLabels[interest.status]}</span></div><p className="mt-2 text-sm leading-6 text-muted">{interest.message || 'Interesse esportivo sem mensagem.'}</p>{interest.status === 'ACEITO' && interest.contactEmail && <a className="mt-3 inline-flex items-center gap-2 text-sm font-black text-neon underline" href={`mailto:${interest.contactEmail}`}><Mail className="h-4 w-4" />{interest.contactEmail}</a>}<div className="mt-3 flex flex-wrap gap-2">{requestDirection === 'RECEBIDOS' && interest.status === 'PENDENTE' && <><button className="neon-button inline-flex min-h-11 items-center gap-2 rounded-lg px-3 py-2 text-sm font-black" type="button" disabled={submitting} onClick={() => void respond(interest.id, true)}><Check className="h-4 w-4" />Aceitar</button><button className="ghost-button inline-flex min-h-11 items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold" type="button" disabled={submitting} onClick={() => void respond(interest.id, false)}><X className="h-4 w-4" />Recusar</button></>}{requestDirection === 'ENVIADOS' && ['PENDENTE', 'ACEITO'].includes(interest.status) && <button className="ghost-button min-h-11 rounded-lg px-3 py-2 text-sm font-bold text-[var(--danger)]" type="button" onClick={() => setCancelInterestId(interest.id)}>Cancelar interesse</button>}</div></div></div></article>; })}{interests.length === 0 && <EmptyState title="Nenhuma solicitação" description={requestDirection === 'RECEBIDOS' ? 'Novos interesses enviados a você aparecerão aqui.' : 'Os interesses que você enviar aparecerão aqui.'} />}</div></div></Modal>

    <ConfirmDialog open={Boolean(cancelInterestId)} title="Cancelar interesse?" description="A outra pessoa verá a solicitação como cancelada e o contato deixará de ficar disponível." confirmLabel="Cancelar interesse" onClose={() => setCancelInterestId('')} onConfirm={async () => { await cancelPartnerInterest(cancelInterestId, user); setCancelInterestId(''); setToast('Interesse cancelado.'); }} />
    <Toast message={toast} onClose={() => setToast('')} />
  </>;
}
