import { Camera, CheckCircle2, Clock3, CreditCard, KeyRound, MapPin, Save, Shield, Trash2, Trophy, UserRound } from 'lucide-react';
import { ChangeEvent, FormEvent, useMemo, useState } from 'react';
import { Avatar } from '../../components/Avatar';
import { Modal } from '../../components/Modal';
import { StatusBadge } from '../../components/StatusBadge';
import { Toast } from '../../components/Toast';
import { useAppData } from '../../contexts/AppDataContext';
import { useAuth } from '../../contexts/AuthContext';
import type { Modality, User, UserPreferences } from '../../lib/types';

const modalities: Modality[] = ['Beach Tennis', 'Futevôlei', 'Society', 'Tênis', 'Vôlei', 'Basquete'];
const currency = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const formatDate = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`));

function Header({ title, subtitle }: { title: string; subtitle: string }) {
  return <header className="mb-6"><p className="text-sm font-black uppercase text-neon">Sua conta PlaySpace</p><h1 className="mt-1 text-3xl font-black">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{subtitle}</p></header>;
}

export function ProfilePage() {
  const { user, updateSessionUser } = useAuth();
  const { dataSource, removeCurrentAvatar, saveCurrentProfile, changeCurrentPassword, state } = useAppData();
  const [draft, setDraft] = useState<User | null>(() => user ? JSON.parse(JSON.stringify(user)) as User : null);
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [passwords, setPasswords] = useState({ current: '', next: '', confirmation: '' });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  if (!user || !draft) return null;
  const reservations = state.reservations.filter((item) => item.clientId === user.id).sort((a, b) => `${b.date}${b.startTime}`.localeCompare(`${a.date}${a.startTime}`));
  const reservationIds = new Set(reservations.map((item) => item.id));
  const payments = state.payments.filter((item) => reservationIds.has(item.reservationId));
  const reviews = state.reviews.filter((item) => item.userName === user.name);
  const achievements = state.achievements[user.id] ?? [];

  const save = async (event: FormEvent) => {
    event.preventDefault(); if (submitting) return;
    setSubmitting(true); setError('');
    try { const saved = await saveCurrentProfile(draft); updateSessionUser(saved); setDraft(JSON.parse(JSON.stringify(saved))); setToast('Perfil atualizado com sucesso.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar o perfil.'); }
    finally { setSubmitting(false); }
  };
  const removeAvatar = async () => {
    setSubmitting(true); setError('');
    try { const saved = await removeCurrentAvatar(draft); updateSessionUser(saved); setDraft(saved); setToast('Foto removida.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível remover a foto.'); }
    finally { setSubmitting(false); }
  };
  const pickImage = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    if (!file.type.startsWith('image/') || file.size > 1_500_000) { setError('Escolha uma imagem de até 1,5 MB.'); return; }
    const reader = new FileReader();
    reader.onload = () => setDraft((current) => current ? { ...current, profile: { ...current.profile, photo: String(reader.result) } } : current);
    reader.readAsDataURL(file);
  };
  const changePassword = async (event: FormEvent) => {
    event.preventDefault(); if (submitting) return;
    setSubmitting(true); setError('');
    try { await changeCurrentPassword(user, passwords.current, passwords.next, passwords.confirmation); setPasswordOpen(false); setPasswords({ current: '', next: '', confirmation: '' }); setToast('Senha alterada com sucesso.'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível alterar a senha.'); }
    finally { setSubmitting(false); }
  };

  return <>
    <Header title="Meu perfil" subtitle="Atualize seus dados pessoais, identidade esportiva, foto e senha em um único lugar." />
    <form className="grid items-start gap-4 xl:grid-cols-[20rem_1fr]" onSubmit={save}>
      <aside className="glass-panel rounded-lg p-5 text-center xl:sticky xl:top-24"><Avatar name={draft.name} src={draft.profile.photo} size={104} className="mx-auto border-4 border-[var(--surface-elevated)] text-2xl" /><h2 className="mt-4 text-xl font-black">{draft.name}</h2><p className="break-all text-sm text-muted">{draft.email}</p><div className="mt-5 grid gap-2">{dataSource === 'demo' ? <label className="ghost-button inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold"><Camera className="h-4 w-4" />Escolher foto<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={pickImage} /></label> : <label className="grid gap-2 text-left text-sm font-bold">URL pública do avatar<input className="app-input min-w-0" type="url" value={draft.profile.photo.startsWith('http') ? draft.profile.photo : ''} placeholder="https://..." onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, photo: event.target.value } })} /></label>}<button className="ghost-button inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-[var(--danger)]" type="button" disabled={!draft.profile.photo || submitting} onClick={() => void removeAvatar()}><Trash2 className="h-4 w-4" />Remover foto</button><button className="ghost-button inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold" type="button" onClick={() => { setError(''); setPasswordOpen(true); }}><KeyRound className="h-4 w-4" />Trocar senha</button></div><p className="mt-4 text-xs leading-5 text-muted">{dataSource === 'api' ? 'A URL é persistida no perfil conectado à API.' : 'No modo demo, a foto escolhida permanece salva neste navegador.'}</p></aside>
      <div className="grid gap-4"><section className="glass-panel rounded-lg p-5"><h2 className="text-lg font-black">Informações pessoais</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Nome completo<input className="app-input" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} maxLength={255} required /></label><label className="grid gap-2 text-sm font-bold">E-mail<input className="app-input opacity-70" value={draft.email} disabled aria-describedby="email-help" /><span id="email-help" className="text-xs font-normal text-muted">O e-mail de acesso é alterado pela administração.</span></label><label className="grid gap-2 text-sm font-bold">Telefone<input className="app-input" value={draft.profile.phone ?? ''} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, phone: event.target.value } })} inputMode="tel" maxLength={30} placeholder="(11) 99999-9999" /></label><label className="grid gap-2 text-sm font-bold">Cidade<input className="app-input" value={draft.profile.city} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, city: event.target.value } })} maxLength={120} /></label><label className="grid gap-2 text-sm font-bold md:col-span-2">Biografia<textarea className="app-input min-h-28 resize-y" value={draft.profile.bio} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, bio: event.target.value } })} maxLength={255} placeholder="Conte um pouco sobre sua relação com o esporte." /></label></div></section>
        <section className="glass-panel rounded-lg p-5"><h2 className="text-lg font-black">Identidade esportiva</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Modalidade favorita<select className="app-input" value={draft.profile.favoriteModality} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, favoriteModality: event.target.value as Modality } })}>{modalities.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Nível esportivo<select className="app-input" value={draft.profile.level} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, level: event.target.value as User['profile']['level'] } })}><option>Iniciante</option><option>Intermediário</option><option>Avançado</option><option>Competitivo</option></select></label><fieldset className="md:col-span-2"><legend className="text-sm font-bold">Modalidades praticadas</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{modalities.map((item) => <label key={item} className="soft-panel flex min-h-11 items-center gap-3 rounded-lg p-3 text-sm font-bold"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={draft.profile.sports.includes(item)} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, sports: event.target.checked ? [...draft.profile.sports, item] : draft.profile.sports.filter((sport) => sport !== item) } })} />{item}</label>)}</div></fieldset><label className="grid gap-2 text-sm font-bold md:col-span-2">Disponibilidade geral<textarea className="app-input min-h-24 resize-y" value={draft.profile.availability ?? ''} onChange={(event) => setDraft({ ...draft, profile: { ...draft.profile, availability: event.target.value } })} maxLength={1000} placeholder="Ex.: segunda e quarta, das 18:00 às 21:00" /></label></div></section>
        {error && <p className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="flex justify-end"><button className="neon-button inline-flex min-h-12 items-center gap-2 rounded-lg px-5 py-3 font-black disabled:opacity-60" type="submit" disabled={submitting}><Save className="h-4 w-4" />{submitting ? 'Salvando...' : 'Salvar alterações'}</button></div>
      </div>
    </form>

    <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Clock3, 'Reservas realizadas', String(reservations.length)], [CreditCard, 'Total pago', currency(payments.filter((item) => item.status === 'Aprovado').reduce((sum, item) => sum + item.amount, 0))], [Trophy, 'Conquistas', String(achievements.filter((item) => item.percent >= 100).length)], [CheckCircle2, 'Avaliações', String(reviews.length)]].map(([Icon, label, value]) => { const Component = Icon as typeof Clock3; return <div key={String(label)} className="glass-panel rounded-lg p-4"><Component className="h-5 w-5 text-neon" /><p className="mt-3 text-sm text-muted">{String(label)}</p><strong className="text-xl">{String(value)}</strong></div>; })}</section>
    <section className="glass-panel mt-4 rounded-lg p-5"><h2 className="text-lg font-black">Histórico recente</h2><div className="mt-4 grid gap-3">{reservations.slice(0, 6).map((reservation) => <div key={reservation.id} className="soft-panel flex flex-wrap items-center justify-between gap-3 rounded-lg p-3"><div><p className="font-bold">{reservation.courtName}</p><p className="text-sm text-muted">{formatDate(reservation.date)} · {reservation.startTime}–{reservation.endTime} · {reservation.code}</p></div><StatusBadge status={reservation.status} compact /></div>)}{reservations.length === 0 && <p className="text-sm text-muted">Nenhuma reserva registrada.</p>}</div></section>

    <Modal title="Trocar senha" open={passwordOpen} onClose={() => setPasswordOpen(false)} maxWidth="max-w-lg"><form className="grid gap-4" onSubmit={changePassword}><label className="grid gap-2 text-sm font-bold">Senha atual<input className="app-input" type="password" autoComplete="current-password" value={passwords.current} onChange={(event) => setPasswords({ ...passwords, current: event.target.value })} required /></label><label className="grid gap-2 text-sm font-bold">Nova senha<input className="app-input" type="password" autoComplete="new-password" value={passwords.next} onChange={(event) => setPasswords({ ...passwords, next: event.target.value })} minLength={8} required /><span className="text-xs font-normal text-muted">Use maiúscula, minúscula, número e pelo menos 8 caracteres.</span></label><label className="grid gap-2 text-sm font-bold">Confirmar nova senha<input className="app-input" type="password" autoComplete="new-password" value={passwords.confirmation} onChange={(event) => setPasswords({ ...passwords, confirmation: event.target.value })} minLength={8} required /></label>{error && <p className="text-sm text-[var(--danger)]" role="alert">{error}</p>}<div className="flex justify-end gap-2"><button className="ghost-button min-h-11 rounded-lg px-4 py-2 font-bold" type="button" onClick={() => setPasswordOpen(false)}>Cancelar</button><button className="neon-button min-h-11 rounded-lg px-4 py-2 font-black" type="submit" disabled={submitting}>{submitting ? 'Alterando...' : 'Alterar senha'}</button></div></form></Modal>
    <Toast message={toast} onClose={() => setToast('')} />
  </>;
}

export function PreferencesPage() {
  const { user } = useAuth();
  const { saveUserPreferences, state } = useAppData();
  const defaults: UserPreferences = { theme: 'SYSTEM', notificationsEnabled: true, reservationReminderHours: 2, emailNotifications: true, browserNotifications: true, defaultCity: user?.profile.city ?? '', favoriteModalities: user ? [user.profile.favoriteModality] : [], preferredTimes: '', privateProfile: false, discoverableByPartners: true, language: 'pt-BR' };
  const [draft, setDraft] = useState<UserPreferences>(() => user ? { ...defaults, ...(state.userPreferences[user.id] ?? {}) } : defaults);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  if (!user) return null;
  const save = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(''); try { const saved = await saveUserPreferences(user.id, draft); setDraft(saved); setToast('Preferências salvas.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar as preferências.'); } finally { setSubmitting(false); } };
  return <><Header title="Preferências" subtitle="Personalize tema, notificações, privacidade e recomendações esportivas. As alterações persistem entre acessos." /><form className="grid gap-4 xl:grid-cols-2" onSubmit={save}><section className="glass-panel rounded-lg p-5"><h2 className="flex items-center gap-2 text-lg font-black"><UserRound className="h-5 w-5 text-neon" />Experiência</h2><div className="mt-4 grid gap-4"><label className="grid gap-2 text-sm font-bold">Tema<select className="app-input" value={draft.theme} onChange={(event) => setDraft({ ...draft, theme: event.target.value as UserPreferences['theme'] })}><option value="SYSTEM">Seguir o sistema</option><option value="LIGHT">Claro</option><option value="DARK">Escuro</option></select></label><label className="grid gap-2 text-sm font-bold">Cidade padrão<input className="app-input" value={draft.defaultCity} onChange={(event) => setDraft({ ...draft, defaultCity: event.target.value })} maxLength={120} /></label><label className="grid gap-2 text-sm font-bold">Horários preferidos<textarea className="app-input min-h-24 resize-y" value={draft.preferredTimes} onChange={(event) => setDraft({ ...draft, preferredTimes: event.target.value })} maxLength={1000} placeholder="Dias úteis, das 18:00 às 21:00" /></label><label className="grid gap-2 text-sm font-bold">Idioma<select className="app-input" value={draft.language} onChange={(event) => setDraft({ ...draft, language: event.target.value as UserPreferences['language'] })}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English</option><option value="es-ES">Español</option></select></label></div></section>
    <section className="glass-panel rounded-lg p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Clock3 className="h-5 w-5 text-neon" />Notificações</h2><div className="mt-4 grid gap-3">{[['notificationsEnabled', 'Ativar notificações', 'Avisos dentro do PlaySpace.'], ['emailNotifications', 'Receber por e-mail', 'Confirmações e atualizações importantes.'], ['browserNotifications', 'Notificações no navegador', 'Alertas mesmo com outra aba aberta.']].map(([key, label, description]) => <label key={key} className="soft-panel flex min-h-16 items-center gap-3 rounded-lg p-3"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={Boolean(draft[key as keyof UserPreferences])} onChange={(event) => setDraft({ ...draft, [key]: event.target.checked })} /><span><strong className="block text-sm">{label}</strong><span className="text-xs text-muted">{description}</span></span></label>)}<label className="grid gap-2 text-sm font-bold">Lembrete de reserva<select className="app-input" value={draft.reservationReminderHours} onChange={(event) => setDraft({ ...draft, reservationReminderHours: Number(event.target.value) })}><option value={0}>Sem lembrete</option><option value={1}>1 hora antes</option><option value={2}>2 horas antes</option><option value={6}>6 horas antes</option><option value={24}>1 dia antes</option></select></label></div></section>
    <section className="glass-panel rounded-lg p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Trophy className="h-5 w-5 text-neon" />Modalidades favoritas</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{modalities.map((item) => <label key={item} className="soft-panel flex min-h-11 items-center gap-3 rounded-lg p-3 text-sm font-bold"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={draft.favoriteModalities.includes(item)} onChange={(event) => setDraft({ ...draft, favoriteModalities: event.target.checked ? [...draft.favoriteModalities, item] : draft.favoriteModalities.filter((modality) => modality !== item) })} />{item}</label>)}</div></section>
    <section className="glass-panel rounded-lg p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Shield className="h-5 w-5 text-neon" />Privacidade</h2><div className="mt-4 grid gap-3"><label className="soft-panel flex min-h-16 items-center gap-3 rounded-lg p-3"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={draft.privateProfile} onChange={(event) => setDraft({ ...draft, privateProfile: event.target.checked })} /><span><strong className="block text-sm">Perfil privado</strong><span className="text-xs text-muted">Limita informações visíveis na comunidade.</span></span></label><label className="soft-panel flex min-h-16 items-center gap-3 rounded-lg p-3"><input className="h-5 w-5 accent-[var(--primary)]" type="checkbox" checked={draft.discoverableByPartners} onChange={(event) => setDraft({ ...draft, discoverableByPartners: event.target.checked })} /><span><strong className="block text-sm">Aparecer na busca de parceiros</strong><span className="text-xs text-muted">Permite que jogadores encontrem seu perfil esportivo.</span></span></label></div></section>
    {error && <p className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-[var(--danger)] xl:col-span-2" role="alert">{error}</p>}<div className="flex justify-end xl:col-span-2"><button className="neon-button inline-flex min-h-12 items-center gap-2 rounded-lg px-5 py-3 font-black disabled:opacity-60" type="submit" disabled={submitting}><Save className="h-4 w-4" />{submitting ? 'Salvando...' : 'Salvar preferências'}</button></div></form><Toast message={toast} onClose={() => setToast('')} /></>;
}
